# Generated by Django 5.1.15 on 2026-09-19 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-mountain-sun', help_text='FontAwesome icon class (e.g., fa-mountain-sun, fa-landmark-dome, fa-umbrella-beach, fa-paw)', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destination Category',
                'verbose_name_plural': 'Destination Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(help_text='City, State / Country (e.g., Manali, Himachal Pradesh)', max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('highlights', models.TextField(help_text='Key highlights/attractions (one per line or comma-separated)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='destinations.destinationcategory')),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Package Name')),
                ('description', models.TextField()),
                ('duration_days', models.PositiveIntegerField(default=3, help_text='Duration in days (used for numeric filtering and sorting)')),
                ('duration', models.CharField(blank=True, help_text="Display duration text (e.g., '4 Days / 3 Nights')", max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price per person in INR', max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('inclusions', models.TextField(blank=True, help_text='Items included in this package (enter one per line)')),
                ('exclusions', models.TextField(blank=True, help_text='Items excluded from this package (enter one per line)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'Tour Package',
                'verbose_name_plural': 'Tour Packages',
                'ordering': ['base_price'],
            },
        ),
        migrations.CreateModel(
            name='PackageItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(default=1, verbose_name='Day Number')),
                ('title', models.CharField(help_text='e.g., Arrival in Manali & Local Acclimatization', max_length=200)),
                ('description', models.TextField()),
                ('activities', models.TextField(blank=True, help_text='Key activities/sites visited on this day (enter one per line or comma-separated)')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='destinations.tourpackage')),
            ],
            options={
                'verbose_name': 'Package Itinerary',
                'verbose_name_plural': 'Package Itineraries',
                'ordering': ['day_number'],
                'unique_together': {('package', 'day_number')},
            },
        ),
    ]
