# Generated by Django 5.1.15 on 2026-09-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_seed_initial_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationcategory',
            name='best_suited_activities',
            field=models.CharField(blank=True, help_text='Key activities suitable for this category', max_length=255),
        ),
        migrations.AddField(
            model_name='destinationcategory',
            name='popular_experiences',
            field=models.CharField(blank=True, help_text='Comma-separated popular experiences (e.g., Trekking, Rafting)', max_length=255),
        ),
        migrations.AddField(
            model_name='destinationcategory',
            name='recommended_for',
            field=models.CharField(blank=True, help_text='Target audience (e.g., Adventure lovers, Groups)', max_length=255),
        ),
    ]
