# Generated by Django 5.1.15 on 2026-09-21 04:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0002_seed_initial_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Peak Summer Season, Festive Diwali Season, Monsoon Saver', max_length=100, verbose_name='Season Name')),
                ('start_date', models.DateField(help_text='Season start date (YYYY-MM-DD)')),
                ('end_date', models.DateField(help_text='Season end date (YYYY-MM-DD)')),
                ('multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplier applied to subtotal (e.g. 1.20 for +20% peak, 0.90 for -10% discount)', max_digits=5)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('description', models.TextField(blank=True, help_text='Details about seasonality reasons (holidays, weather, peak demand)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seasonal Pricing Rule',
                'verbose_name_plural': 'Seasonal Pricing Rules',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Maruti Suzuki Dzire, Toyota Innova Crysta, Force Urbania', max_length=150, verbose_name='Vehicle Name/Model')),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('minibus', 'Minibus')], default='sedan', max_length=20, verbose_name='Vehicle Category')),
                ('seating_capacity', models.PositiveIntegerField(default=4, help_text='Maximum passenger capacity excluding driver')),
                ('rate_per_day', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Daily rental charge in INR', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Vehicle specifications, air conditioning, luggage capacity, etc.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['vehicle_type', 'rate_per_day'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Hotel Name')),
                ('location', models.CharField(blank=True, help_text='Detailed address/area (e.g., Near Mall Road, Manali)', max_length=255)),
                ('tier', models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('premium', 'Premium')], default='standard', max_length=20, verbose_name='Hotel Tier')),
                ('description', models.TextField(help_text='Overview of hotel features and hospitality services')),
                ('room_type', models.CharField(default='Standard Double Room', help_text='e.g. Deluxe Double Room, Premium View Suite, Executive Twin', max_length=100)),
                ('price_per_night', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Surcharge or price per room per night in INR', max_digits=10)),
                ('available_rooms', models.PositiveIntegerField(default=10, help_text='Current available inventory of rooms')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(help_text='Tourist destination where this hotel is located', on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'ordering': ['destination', 'price_per_night'],
            },
        ),
    ]
